### ISSUE TITLE
Angular Vienna Logo suggestions

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/angular-vienna-logo#1]
This is the call to propose logo for Angular Vienna meetup.
Logo should ideally symbolize and show clear link to:
* Angular
* Vienna

Regarding Angular, you can use just color from the logo, or just a shape, or only the parts of it, but at the end it should be clear (to devs at least) that it's related to Angular.

Regarding Vienna, think what is Vienna famous for? Schnitzel? Mozart? Coffee? Prater? Sacher? Or something else...? Think about how would we depict this in logo.

Logo should be simple, ideally in [vector](https://en.wikipedia.org/wiki/Vector_graphics), but feel free to send just a sketches if your Photoshop/Illustrator/Sketch etc. skills are not on a high level.

We do expect following information:

# Image
Your logo in one of the web graphical formats (GIF, JPEG, PNG, PDF) embedded in the page.

# Description
Describe elements on the logo. (If not clear) describe how these elements relate to Angular and Austria.

# Specs
Any special limitations or necessary information.

## Colors (if different than official Angular's logo)
Colors in HEX (web colors preferred) if different than colors from official Angular's logo

## Font (if relevant)
Please provide the name(s) and make sure they are open source.

# Source
The logo source. You can provide multiple formats.

# License
Is your logo final or a sketch that someone can refine to final version.

# Contact
E-Mail, Twitter or something else

**Comment by meeroslav** [comment]
Let me be the first one to suggest...

![angular-vienna](https://user-images.githubusercontent.com/881612/33324187-2f3c07f8-d44f-11e7-83e5-ea2bb64bf1a2.png)

**Description**
Simple mashup of Angular logo and a circle representing together Wiener Riesenrad in Prater.

**Specs**
As provided by .AI file in source

**Color**
As provided by the original Angular logo

**Font**
None. `A` is a shape from original Angular logo

**Source**
[angular_vienna_by_meeroslav.zip](https://github.com/BioPhoton/angular-vienna-theme/files/1510240/angular_vienna_by_meeroslav.zip)

**Contact**
As provided by the github handle.

**License**
Logo is considered final. If someone has improvement points, contact the author first.

**Comment by joaogarin** [comment]
Some more food for thought!

![angularvienna2](https://user-images.githubusercontent.com/2866604/33629675-d13ef882-d9fc-11e7-9b07-fafa35242815.png)




**Description**
Simple mashup of Angular logo and an icon with the icon karlsplatz cathedral

**Specs**
As provided by .svg file in source

**Color**
As provided by the original Angular logo

**Font**
N/A

**Source**
[angular-vienna.zip](https://github.com/BioPhoton/angular-vienna-logo/files/1533243/angular-vienna.zip)


**Contact**
As provided by the github handle.

**License**
Icon is license under creative commons so proper credit would have to be added in a about us page in the meetup group or any other place https://creativecommons.org/licenses/by/3.0/us/legalcode

**Comment by meeroslav** [comment]
@joaogarin You forgot to provide source.

**Comment by meeroslav** [comment]
![angular vienna 2](https://user-images.githubusercontent.com/881612/39013419-9ccf06a2-4417-11e8-92f9-d8bbbd9b07be.png)
![angular vienna 3](https://user-images.githubusercontent.com/881612/39013420-9ce9066a-4417-11e8-8f85-d7f728f17a3d.png)
![angular vienna](https://user-images.githubusercontent.com/881612/39013422-9d1fd24e-4417-11e8-8ec2-b84b4c586f72.png)

**Description**
Three more variants of Wiener Riesenrad in Prater.

**Comment by meeroslav** [comment]
![angular vienna 4](https://user-images.githubusercontent.com/881612/39013549-fa2dfb8c-4417-11e8-88bb-3c7e2bc00722.png)


**Description**
Simple combination of letters A and W - Angular Wien

**Specs**
As provided by .AI file in source

**Color**
As provided by the original Angular logo

**Font**
None. `A` is a shape from original Angular logo

**Contact**
As provided by the github handle.

**License**
Logo is considered final. If someone has improvement points, contact the author first.

**Comment by meeroslav** [comment]
![image](https://user-images.githubusercontent.com/881612/39013584-196e34ee-4418-11e8-8951-296897744db9.png)

**Description:**
Angular shield with Mozart's wig. Mozart is one of most recognisable symbols of Austria and Vienna.

**License:**
Logo is considered final. If someone has improvement points, contact author first.

**Comment by MovGP0** [comment]
unsure what Mozart has to do with Vienna. Would make a better symbol for the Salzburg group.

**Comment by BioPhoton** [comment]
Hi @MovGP0,
Thx for your feedback. 

This issue is already closed.
The "wiener riesenrad" version is now the official logi for angular-vienna.

We also presented it on the last meetup. 

Best
Michael

**Comment by fmalcher** [comment]
Maybe add the official logo to this repo? 😎
https://github.com/maartentibau/angular-logos

**Comment by meeroslav** [comment]
@fmalcher Will do, thanks
