### ISSUE TITLE
Angular Austria Logo suggestions

### ISSUE THREAD

**Issue by meeroslav** [BioPhoton/angular-vienna-logo#2]
This is the call to propose logo for Angular Austria organization.
Logo should ideally symbolize and show clear link to:
* Angular
* Austria

Regarding Angular, you can use just color from the logo, or just a shape, or only the parts of it, but at the end it should be clear (to devs at least) that it's related to Angular.

Regarding Austria, think what is Austria famous for? Schnitzel? Mozart? Alps? Skiing? Or something else...? Think about how would we depict this in logo.

Logo should be simple, ideally in [vector](https://en.wikipedia.org/wiki/Vector_graphics), but feel free to send just a sketches if your Photoshop/Illustrator/Sketch etc. skills are not on a high level.

We do expect following information:

# Image
Your logo in one of the web graphical formats (GIF, JPEG, PNG, PDF) embedded on the page.

# Source

The logo source. You can provide multiple formats.

# Description

Describe elements on the logo. (If not clear) describe how these elements relate to Angular and Austria.

# Specs

Any special limitations or necessary information.

## Colors (if different than official Angular's logo)

Colors in HEX (web colors preferred) if different than colors from official Angular's logo

## Font (if relevant)

Please provide the name(s) and make sure they are open source.

# License

Is your logo final or a sketch that someone can refine to final version.

**Comment by meeroslav** [comment]
![angular-at-1](https://user-images.githubusercontent.com/881612/33326012-0eb28caa-d454-11e7-87b2-50023fc6f4eb.png)

**Source:** 
[angular at 1.ai.zip](https://github.com/BioPhoton/angular-vienna-theme/files/1510343/angular.at.1.ai.zip)

**Description:**
Angular logo with skier shredding down the letter 'A'. Austria is famous for skiing so why not use it in NG Austria logo.

**License:**
Logo is considered final. If someone has improvement points, contact author first.

**Comment by meeroslav** [comment]
![angular-at-5](https://user-images.githubusercontent.com/881612/33327582-25dde646-d458-11e7-9840-fbf571d29d7d.png)

**Source:** 
[angular at 5.ai.zip](https://github.com/BioPhoton/angular-vienna-theme/files/1510454/angular.at.5.ai.zip)

**Description:**
Angular shield with pair of skis representing letter `A`. Austria is famous for skiing so why not use it in NG Austria logo.

**License:**
Logo is considered final. If someone has improvement points, contact author first.

**Comment by MovGP0** [comment]
I disagree with the `*.gif`, `*.jpeg`, and `*.png` file formats. SVG is much better for this task, since it is a scaleable vector format, it works on the web, there are free editors like [Inkscape](https://inkscape.org/en/), and you can export to other formats as needed.

**Comment by meeroslav** [comment]
@MovGP0, these formats are just for visual representation here. It's quicker and simpler going through the proposals.
You should upload your source file (.cdr, .ai, .pdf, .eps, .svg...) however in the source part.

Additionally, not everyone has skills in one of the vector editors, but they might have an awesome idea. That's why we accept sketches on piece of napkin. We can vectorize this idea later, but if we limit people in formats we might not get those ideas in the first place.

Github supports embedding/attaching following file types: GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX and ZIP.

**Comment by joaogarin** [comment]
![angularat](https://user-images.githubusercontent.com/2866604/33630008-cab33842-d9fd-11e7-9b23-8f7e0ea641a5.png)



**Description:**
Angular shield featuring the official Austria shield as mash. the shield in the eagle was also replaced by the original angular shield.

**Comment by joaogarin** [comment]
![angularat2](https://user-images.githubusercontent.com/2866604/33630271-a237be00-d9fe-11e7-8998-a481ace6477b.png)


Just some more ideas, let me know if its too far off lol

**Comment by meeroslav** [comment]
![angular at mozart](https://user-images.githubusercontent.com/881612/34641811-fd18307e-f309-11e7-9eab-7037d19c391f.png)

**Source:**
[angular at mozart.ai.zip](https://github.com/BioPhoton/angular-vienna-logo/files/1609003/angular.at.mozart.ai.zip)

**Description:**
Angular shield with Mozart's wig. Mozart is one of most recognisable symbols.

**License:**
Logo is considered final. If someone has improvement points, contact author first.

**Comment by mjurisic** [comment]
I always associated Austria with mountains so my logo idea goes in this direction, 2 As for AngularAustria in Austrian flag colors aligned as mountains:

![angular_austria_v1](https://user-images.githubusercontent.com/6647900/34763399-4e58e260-f5eb-11e7-9e9c-badd33f05a65.png)

Source:
[angular_austria_v1.zip](https://github.com/BioPhoton/angular-vienna-logo/files/1618091/angular_austria_v1.zip)

Description:
Angular logo with 2 As representing mountains

License:
Logo is considered final. If someone has improvement points, contact author first.

**Comment by mjurisic** [comment]
Another version with Prater Riesenrad in the backround.

![angular_austria_v2](https://user-images.githubusercontent.com/6647900/34763484-aaeae474-f5eb-11e7-9f58-23356cbb3e8e.png)


Source:
[angular_austria_v2.zip](https://github.com/BioPhoton/angular-vienna-logo/files/1618092/angular_austria_v2.zip)


Description:
Angular logo with 2 As representing mountains and Riesenrad in the background.

License:
Logo is considered final. If someone has improvement points, contact author first.

**Comment by meeroslav** [comment]
![franz josef](https://user-images.githubusercontent.com/881612/37463174-b06b3250-2854-11e8-9c40-f93ee4a1c6d1.png)

**Source:**
[angular at franz josef no hair.ai.zip](https://github.com/BioPhoton/angular-vienna-logo/files/1815253/angular.at.franz.josef.no.hair.ai.zip)


**Description:**
Angular shield with Franz Josef's beard and moustache.

**License:**
Logo is not yet considered final. Every improvement is welcome.
